controllers:
    resource: ../../src/Controller/
    type: attribute

kernel:
    resource: ../../src/Kernel.php
    type: attribute

backend_errorea:
    path:     admin/errorea
    defaults: { _controller: App::Default::errorea  }
