controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

backend_errorea:
    path:     admin/errorea
    defaults: { _controller: App::Default::errorea  }
